"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  ArrowRight,
  Building2,
  Truck,
  TrendingUp,
  Network,
  CheckCircle2,
} from "lucide-react";

const partnershipOptions = [
  {
    number: "01",
    title: "Location Partner",
    description:
      "Have a property in a strategic location? Host a Topup charging station and create a new revenue opportunity.",
    icon: Building2,
    href: "/partner/location",
  },
  {
    number: "02",
    title: "Fleet Partner",
    description:
      "Operate an EV fleet? We can build charging infrastructure around your vehicles, routes and operating needs.",
    icon: Truck,
    href: "/partner/fleet",
  },
  {
    number: "03",
    title: "Franchise Partner",
    description:
      "Looking to invest in the EV transition? Partner with Topup to participate in charging infrastructure development.",
    icon: TrendingUp,
    href: "/partner/franchise",
  },
  {
    number: "04",
    title: "Network Partner",
    description:
      "Already operate EV chargers? Bring your existing infrastructure onto the Topup network.",
    icon: Network,
    href: "/partner/network",
  },
];

const commercialModels = [
  {
    title: "Rent",
    description:
      "Provide your property to Topup and receive an agreed rental amount.",
  },
  {
    title: "Revenue Sharing",
    description:
      "Share in the revenue generated by charging activity at your location.",
  },
  {
    title: "Invest & Share",
    description:
      "Participate in the investment and share in the long-term returns from the charging station.",
  },
];

const steps = [
  {
    number: "01",
    title: "Tell us about your opportunity",
    description:
      "Share some basic information about your property, fleet, infrastructure or investment interest.",
  },
  {
    number: "02",
    title: "We evaluate the opportunity",
    description:
      "Our team reviews the location, requirements and potential to understand whether it is a good fit.",
  },
  {
    number: "03",
    title: "We agree on the partnership",
    description:
      "We discuss the right commercial structure, responsibilities and next steps.",
  },
  {
    number: "04",
    title: "We build together",
    description:
      "Once everything is agreed, we move towards deployment and building the charging solution.",
  },
];

export default function PartnerPage() {
  return (
    <main className="bg-white text-[#111]">
      {/* =========================================================
          HERO
      ========================================================= */}

      <section data-navbar-theme="light" className="relative overflow-hidden bg-[#F7F5F1]">
        <div className="mx-auto max-w-[1500px] px-6 pb-24 pt-32 md:px-10 md:pb-28 md:pt-40 lg:px-14 lg:pb-36">
          <div className="grid gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-end">
            <motion.div
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <div className="mb-7 flex items-center gap-4">
                <span className="h-px w-10 bg-[#FF8000]" />

                <span className="text-[10px] font-semibold uppercase tracking-[0.28em] text-black/50">
                  Partner with Topup
                </span>
              </div>

              <h1 className="max-w-4xl text-[clamp(3.8rem,7.5vw,7.8rem)] font-medium leading-[0.88] tracking-[-0.065em]">
                Build EV charging
                <br />
                <span className="text-black/35">with us.</span>
              </h1>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.15 }}
              className="max-w-lg lg:pb-2"
            >
              <p className="text-base leading-7 text-black/60 md:text-lg md:leading-8">
                Topup works with property owners, fleet operators, businesses
                and investors to build reliable EV charging infrastructure
                across India.
              </p>

              <div className="mt-8 flex flex-wrap gap-5">
                <Link
                  href="#partnership-options"
                  className="group inline-flex items-center gap-6 bg-[#111] px-6 py-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-white transition hover:bg-[#FF8000] hover:text-black"
                >
                  Explore partnerships

                  <ArrowRight
                    size={15}
                    strokeWidth={1.8}
                    className="transition-transform duration-300 group-hover:translate-x-1"
                  />
                </Link>

                <Link
                  href="/contact"
                  className="group inline-flex items-center gap-3 border-b border-black/25 pb-2 pt-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-black/70 transition hover:border-black hover:text-black"
                >
                  Talk to us

                  <ArrowRight
                    size={14}
                    strokeWidth={1.7}
                    className="transition-transform duration-300 group-hover:translate-x-1"
                  />
                </Link>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* =========================================================
          PARTNERSHIP OPTIONS
      ========================================================= */}

      <section
        id="partnership-options"
        data-navbar-theme="light" className="scroll-mt-20 px-6 py-24 md:px-10 lg:px-14 lg:py-32"
      >
        <div className="mx-auto max-w-[1500px]">
          <div className="max-w-3xl">
            <p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-black/40">
              Ways to partner
            </p>

            <h2 className="mt-5 text-[clamp(2.8rem,5vw,5.5rem)] font-medium leading-[0.92] tracking-[-0.055em]">
              How would you like
              <br />
              <span className="text-black/35">to work with Topup?</span>
            </h2>

            <p className="mt-7 max-w-2xl text-base leading-7 text-black/55 md:text-lg md:leading-8">
              Choose the partnership that best matches what you bring to the
              table.
            </p>
          </div>

          <div className="mt-16 grid gap-5 md:grid-cols-2">
            {partnershipOptions.map((option, index) => {
              const Icon = option.icon;

              return (
                <motion.div
                  key={option.number}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-60px" }}
                  transition={{
                    duration: 0.65,
                    delay: index * 0.06,
                  }}
                >
                  <Link
                    href={option.href}
                    className="group block h-full rounded-[2px] border border-black/10 p-7 transition-all duration-300 hover:-translate-y-1 hover:border-black/20 hover:shadow-[0_20px_60px_rgba(0,0,0,0.07)] md:p-9"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex h-11 w-11 items-center justify-center bg-[#F7F5F1]">
                        <Icon
                          size={19}
                          strokeWidth={1.5}
                          className="text-[#FF8000]"
                        />
                      </div>

                      <span className="text-[10px] tracking-[0.2em] text-black/25">
                        {option.number}
                      </span>
                    </div>

                    <h3 className="mt-9 text-2xl font-medium tracking-[-0.035em] md:text-3xl">
                      {option.title}
                    </h3>

                    <p className="mt-4 max-w-lg text-sm leading-6 text-black/55 md:text-[15px]">
                      {option.description}
                    </p>

                    <div className="mt-8 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-black/60 transition-colors group-hover:text-[#FF8000]">
                      Learn more

                      <ArrowRight
                        size={14}
                        strokeWidth={1.7}
                        className="transition-transform duration-300 group-hover:translate-x-1"
                      />
                    </div>
                  </Link>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* =========================================================
          HOW IT WORKS
      ========================================================= */}

      <section data-navbar-theme="light"className="bg-[#F7F5F1] px-6 py-24 md:px-10 lg:px-14 lg:py-32">
        <div className="mx-auto max-w-[1500px]">
          <div className="grid gap-16 lg:grid-cols-[0.7fr_1.3fr] lg:gap-24">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-black/40">
                The process
              </p>

              <h2 className="mt-5 text-[clamp(2.8rem,5vw,5.5rem)] font-medium leading-[0.9] tracking-[-0.055em]">
                Simple from
                <br />
                <span className="text-black/35">the start.</span>
              </h2>

              <p className="mt-7 max-w-md text-base leading-7 text-black/55">
                We keep the process straightforward. Start with an
                opportunity, and we&apos;ll work with you to understand what
                makes sense.
              </p>
            </div>

            <div className="border-t border-black/10">
              {steps.map((step) => (
                <div
                  key={step.number}
                  className="grid gap-5 border-b border-black/10 py-8 md:grid-cols-[70px_1fr] md:gap-8 md:py-9"
                >
                  <span className="text-[10px] font-medium tracking-[0.2em] text-black/30">
                    {step.number}
                  </span>

                  <div>
                    <h3 className="text-xl font-medium tracking-[-0.025em] md:text-2xl">
                      {step.title}
                    </h3>

                    <p className="mt-3 max-w-xl text-sm leading-6 text-black/50 md:text-[15px]">
                      {step.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* =========================================================
          LOCATION PARTNERSHIP
      ========================================================= */}

      <section className="bg-[#111] px-6 py-24 text-white md:px-10 lg:px-14 lg:py-32">
        <div className="mx-auto max-w-[1500px]">
          <div className="grid gap-16 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-[#FF8000]">
                Location partners
              </p>

              <h2 className="mt-5 text-[clamp(2.8rem,5vw,5.5rem)] font-medium leading-[0.9] tracking-[-0.055em]">
                Have a
                <br />
                <span className="text-white/35">location?</span>
              </h2>

              <p className="mt-7 max-w-lg text-base leading-7 text-white/50 md:text-lg md:leading-8">
                If you have a suitable property, there are several ways we
                can structure the partnership.
              </p>

              <Link
                href="/partner/location"
                className="group mt-9 inline-flex items-center gap-4 border-b border-white/20 pb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/75 transition hover:border-[#FF8000] hover:text-white"
              >
                Explore location partnership

                <ArrowRight
                  size={14}
                  strokeWidth={1.7}
                  className="transition-transform duration-300 group-hover:translate-x-1"
                />
              </Link>
            </div>

            <div className="border-t border-white/10">
              {commercialModels.map((model, index) => (
                <div
                  key={model.title}
                  className="grid gap-5 border-b border-white/10 py-9 md:grid-cols-[55px_1fr] md:gap-8"
                >
                  <span className="text-[10px] tracking-[0.2em] text-white/25">
                    0{index + 1}
                  </span>

                  <div>
                    <h3 className="text-2xl font-medium tracking-[-0.03em] md:text-3xl">
                      {model.title}
                    </h3>

                    <p className="mt-3 max-w-xl text-sm leading-6 text-white/45 md:text-[15px]">
                      {model.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* =========================================================
          WHY TOPUP
      ========================================================= */}

      <section data-navbar-theme="light"className="px-6 py-24 md:px-10 lg:px-14 lg:py-32">
        <div className="mx-auto max-w-[1500px]">
          <div className="max-w-3xl">
            <p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-black/40">
              Why partner with Topup
            </p>

            <h2 className="mt-5 text-[clamp(2.8rem,5vw,5.5rem)] font-medium leading-[0.9] tracking-[-0.055em]">
              We&apos;re building for
              <br />
              <span className="text-black/35">the long road.</span>
            </h2>
          </div>

          <div className="mt-16 grid gap-x-10 gap-y-12 border-t border-black/10 pt-10 md:grid-cols-2 lg:grid-cols-3">
            {[
              "Strategic charging locations",
              "Fleet-focused infrastructure",
              "Reliable charging experience",
              "Long-term partnerships",
              "Growing EV network",
              "Focused on South India and beyond",
            ].map((item) => (
              <div key={item} className="flex gap-4">
                <CheckCircle2
                  size={18}
                  strokeWidth={1.5}
                  className="mt-0.5 shrink-0 text-[#FF8000]"
                />

                <p className="text-[15px] leading-6 text-black/60">
                  {item}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =========================================================
          FINAL CTA
      ========================================================= */}

      <section className="bg-[#FF8000] px-6 py-24 md:px-10 lg:px-14 lg:py-32">
        <div className="mx-auto max-w-[1500px]">
          <div className="max-w-5xl">
            <p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-black/45">
              Let&apos;s talk
            </p>

            <h2 className="mt-5 text-[clamp(3.5rem,7vw,8rem)] font-medium leading-[0.84] tracking-[-0.07em]">
              Have an opportunity?
              <br />
              Let&apos;s explore it.
            </h2>

            <p className="mt-8 max-w-xl text-base leading-7 text-black/60 md:text-lg md:leading-8">
              Tell us what you&apos;re looking to build, and our team will
              take it from there.
            </p>

            <Link
              href="/contact"
              className="group mt-9 inline-flex items-center gap-7 bg-black px-7 py-4 text-[11px] font-semibold uppercase tracking-[0.18em] text-white transition hover:bg-white hover:text-black"
            >
              Talk to Topup

              <ArrowRight
                size={15}
                strokeWidth={1.8}
                className="transition-transform duration-300 group-hover:translate-x-1"
              />
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}